/**
 * farmacia.js
 * Repositório central de medicamentos padronizados (Versão 01/2024)
 * Relação completa e fiel extraída dos documentos oficiais para as UPAs.
 */

const medicamentosAcrizioMenezes = [
    // Aminas Vasoativas / Catecolaminas / Cardiotônicos
    { nome: "Deslanosídeo 0,4mg/2ml", apresentacao: "Ampola", via: "EV/IM", observacao: "Glicosídeo cardiotônico" }, //[cite: 2]
    { nome: "Digoxina 0,25mg", apresentacao: "Comprimido", via: "Oral", observacao: "Glicosídeo cardiotônico, inotrópico" }, //[cite: 2]
    { nome: "Dobutamina 250mg/20ml", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Inotrópico" }, //[cite: 2]
    { nome: "Dopamina 50mg/10ml", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Inotrópico" }, //[cite: 2]
    { nome: "Epinefrina (Adrenalina) 1mg/ml", apresentacao: "Ampola", via: "IM/EV/SC", observacao: "Vasopressor" }, //[cite: 2]
    { nome: "Norepinefrina hemitartarato 8mg/4ml", apresentacao: "Ampola", via: "EV Via exclusiva", observacao: "Vasopressor" }, //[cite: 2]

    // Analgésicos e Antitérmicos
    { nome: "Dipirona 500mg/ml", apresentacao: "Gotas - Frasco", via: "Oral", observacao: "20 gotas=1mL" }, //[cite: 2]
    { nome: "Dipirona 1000mg/2mL", apresentacao: "Ampola", via: "IM/EV", observacao: "Menores de 8k somente IM" }, //[cite: 2]
    { nome: "Paracetamol 200mg/mL", apresentacao: "Gotas - Frasco", via: "Oral", observacao: "20 gotas=1mL" }, //[cite: 2]
    { nome: "Paracetamol 500mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]

    // Anti-inflamatórios
    { nome: "Beclometasona 250mcg/jato", apresentacao: "Frasco aerosol", via: "Inalatório", observacao: "Esteroidal" }, //[cite: 2]
    { nome: "Cetoprofeno 100mg/2mL", apresentacao: "Ampola", via: "IM (Via exclusiva)", observacao: "Não esteroidal" }, //[cite: 2]
    { nome: "Cetoprofeno 100mg", apresentacao: "Frasco ampola", via: "EV (Via exclusiva)", observacao: "Não esteroidal" }, //[cite: 2]
    { nome: "Dexametasona 10 mg / 2,5 ml", apresentacao: "Ampola", via: "IM/EV", observacao: "Esteroidal" }, //[cite: 2]
    { nome: "Diclofenaco de Sódio 50 mg", apresentacao: "Comprimido revestido", via: "Oral", observacao: "Não esteroidal" }, //[cite: 2]
    { nome: "Hidrocortisona 100mg", apresentacao: "Frasco ampola", via: "IM/EV", observacao: "Esteroidal" }, //[cite: 2]
    { nome: "Ibuprofeno 50mg/ml", apresentacao: "Gotas", via: "Oral", observacao: "Não esteroidal" }, //[cite: 2]
    { nome: "Ibuprofeno 600mg", apresentacao: "Comprimido", via: "Oral", observacao: "Não esteroidal" }, //[cite: 2]
    { nome: "Metilprednisolona 500mg", apresentacao: "Frasco ampola", via: "IM/EV", observacao: "Esteroidal" }, //[cite: 2]
    { nome: "Prednisolona 3mg/ml", apresentacao: "Suspensão", via: "Oral", observacao: "Esteroidal" }, //[cite: 2]
    { nome: "Prednisona 5mg", apresentacao: "Comprimido", via: "Oral", observacao: "Esteroidal" }, //[cite: 2]
    { nome: "Prednisona 20mg", apresentacao: "Comprimido", via: "Oral", observacao: "Esteroidal" }, //[cite: 2]

    // Anestésicos
    { nome: "Lidocaína 20mg/g", apresentacao: "Gel", via: "Tópico", observacao: "" }, //[cite: 2]
    { nome: "Lidocaína 2% (20mg/mL)", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Lidocaína com Epinefrina 2%", apresentacao: "Ampola", via: "IM/EV", observacao: "Lidocaína com vasoconstritor" }, //[cite: 2]

    // Antiarrítmicos, Anti-hipertensivos, Vasodilatadores
    { nome: "Adenosina 6mg/2ml", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Antiarrítmico" }, //[cite: 2]
    { nome: "Anlodipino 5mg", apresentacao: "Comprimido", via: "Oral", observacao: "Bloq canal Cálcio" }, //[cite: 2]
    { nome: "Atenolol 50 mg", apresentacao: "Comprimido", via: "Oral", observacao: "b-bloqueador" }, //[cite: 2]
    { nome: "Amiodarona 150mg/3ml", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Antiarrítmico" }, //[cite: 2]
    { nome: "Amiodarona 200 mg", apresentacao: "Comprimido", via: "Oral", observacao: "Antiarrítmico" }, //[cite: 2]
    { nome: "Captopril 25mg", apresentacao: "Comprimido", via: "Oral", observacao: "IECA" }, //[cite: 2]
    { nome: "Carvedilol 3,125 mg", apresentacao: "Comprimido", via: "IM/EV", observacao: "b-bloqueador" }, //[cite: 2]
    { nome: "Carvedilol 12,5 mg", apresentacao: "Comprimido", via: "Oral", observacao: "b-bloqueador" }, //[cite: 2]
    { nome: "Enalapril 10mg", apresentacao: "Comprimido", via: "Oral", observacao: "IECA" }, //[cite: 2]
    { nome: "Hidralazina 25mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Isossorbida 5mg", apresentacao: "Comprimido", via: "Sub lingual", observacao: "" }, //[cite: 2]
    { nome: "Isossorbida 20mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Losartana 50mg", apresentacao: "Comprimido", via: "Oral", observacao: "Bloqueador renina-angiotensina" }, //[cite: 2]
    { nome: "Metildopa 250mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Metoprolol 5mg/5mL", apresentacao: "Ampola", via: "EV (via exclusiva)", observacao: "b-bloqueador" }, //[cite: 2]
    { nome: "Nifedipino 20mg", apresentacao: "Comprimido de liberação lenta", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Nitroglicerina 50mg/10mL", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Vasodilatador direto. Requer diluição!" }, //[cite: 2]
    { nome: "Nitroprussiato de Sódio 50mg/2mL", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Vasodilatador direto." }, //[cite: 2]
    { nome: "Propranolol 40mg", apresentacao: "Comprimido", via: "Oral", observacao: "b-bloqueador" }, //[cite: 2]
    { nome: "Verapamil 80mg", apresentacao: "Comprimido", via: "Oral", observacao: "Bloq canal Cálcio" }, //[cite: 2]

    // Antibacterianos
    { nome: "Gentamicina 80mg/2ml", apresentacao: "Ampola", via: "IM/EV", observacao: "Aminoglicosídeos" }, //[cite: 2]
    { nome: "Amoxicilina 50mg/ml", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Amoxicilina 500mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Amoxicilina + Clavulanato 50+12,5 mg/mL", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Amoxicilina + Clavulanato 500+125mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Amoxicilina + Clavulanato 1g+0,2g", apresentacao: "Frasco/ampola", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Ampicilina 1g", apresentacao: "Frasco/ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Benzipenicilina 600.000 UI", apresentacao: "Frasco/ampola", via: "IM (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Benzipenicilina 1.200.000UI", apresentacao: "Frasco/ampola", via: "IM (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Benzipenicilina Potássica 5.000.000", apresentacao: "Frasco-ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Oxacilina 500 mg", apresentacao: "Frasco-ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Cefalexina 50mg/ml", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Cefalexina 500mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Ceftriaxona 1g", apresentacao: "Frasco/ampola", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Cefepima 1g", apresentacao: "Frasco/ampola", via: "IM/EV", observacao: "Requer aprovação CCIH" }, //[cite: 2]
    { nome: "Clindamicina 300mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Clindamicina 600mg/4ml", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Azitromicina 40mg/ml", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Azitromicina 500mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Claritromicina 500mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Metronidazol 250mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Metronidazol 500mg/100ml", apresentacao: "Bolsa", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Ciprofloxacino 200mg/100ml", apresentacao: "Bolsa", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Ciprofloxacino 500mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Sulfametoxazol + Trimetropina 200+4mg/5 mL", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Sulfametoxazol + Trimetropina 400+80mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Sulfadiazina de Prata 1 mg/g", apresentacao: "Creme", via: "Tópica", observacao: "" }, //[cite: 2]
    { nome: "Doxiciclina 100mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "R+I+P+E (150+75+400+275mg)", apresentacao: "Comprimido", via: "Oral", observacao: "1ª fase tuberculose" }, //[cite: 2]
    { nome: "R+I (300+150mg)", apresentacao: "Comprimido", via: "Oral", observacao: "2ª fase tuberculose" }, //[cite: 2]

    // Anticoagulantes, Antiagregantes, Fibrinolíticos
    { nome: "Ácido Acetilsalicílico 100mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Alteplase 50mg/50ml", apresentacao: "Frasco ampola + diluente", via: "EV Via exclusiva", observacao: "Exige justificativa" }, //[cite: 2]
    { nome: "Clopidogrel 75mg", apresentacao: "Comprimido revestido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Heparina 5.000 UI/mL", apresentacao: "Frasco ampola 5mL", via: "EV - BIC", observacao: "Não fracionada" }, //[cite: 2]
    { nome: "Heparina 5.000UI/0,25mL", apresentacao: "Ampola", via: "SC", observacao: "Não fracionada" }, //[cite: 2]
    { nome: "Varfarina 5mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]

    // Antídotos e Antagonistas
    { nome: "Acetilcisteína 300mg/3ml", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Antídoto Paracetamol" }, //[cite: 2]
    { nome: "Atropina 0,25mg/1 ml", apresentacao: "Ampola", via: "IM/EV/SC", observacao: "Antídoto organofosforados" }, //[cite: 2]
    { nome: "Carvão Ativado Pó 25g", apresentacao: "Pacote", via: "Oral via sonda", observacao: "Antídoto inespecífico" }, //[cite: 2]
    { nome: "Dantroleno 20mg", apresentacao: "Frasco ampola + diluente", via: "EV (Via exclusiva)", observacao: "Hipertermia maligna" }, //[cite: 2]
    { nome: "Flumazenil 0,5 mg/5ml", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Antídoto Benzodiazepínicos" }, //[cite: 2]
    { nome: "Naloxona 0,4mg/1mL", apresentacao: "Ampola", via: "IM/SC/EV", observacao: "Antídoto Opióides" }, //[cite: 2]
    { nome: "Poliestirenosulfato de cálcio 900mg/g", apresentacao: "30g/envelope", via: "Oral", observacao: "Sequestrador de Potássio" }, //[cite: 2]
    { nome: "Protamina 5000UI/5mL", apresentacao: "Ampola", via: "EV (Via exclusiva)", observacao: "Antídoto Heparinas" }, //[cite: 2]
    { nome: "Vitamina K (Fitomenadiona) 10 mg/1 ml", apresentacao: "Ampola", via: "IM/SC", observacao: "Antídoto Varfarina" }, //[cite: 2]

    // Antieméticos e Antiespasmódicos
    { nome: "Bromoprida 10mg/2ml", apresentacao: "Ampola", via: "IM/EV", observacao: "Menores de 12a" }, //[cite: 2]
    { nome: "Bromoprida 4mg/ml", apresentacao: "Gotas", via: "Oral", observacao: "Menores de 12a" }, //[cite: 2]
    { nome: "Metoclopramida 10 mg", apresentacao: "Comprimido", via: "Oral", observacao: "Maiores de 12a" }, //[cite: 2]
    { nome: "Metoclopramida 10mg/2mL", apresentacao: "Ampola", via: "IM/EV", observacao: "Maiores de 12a" }, //[cite: 2]
    { nome: "Escopolamina 10mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Escopolamina 20mg/1mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Simeticona 75mg/ml", apresentacao: "Frasco", via: "Oral", observacao: "Antiflatulento" }, //[cite: 2]

    // Antiparasitários, Antifúngicos, Gastro
    { nome: "Ivermectina 6mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Omeprazol 20mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Omeprazol 40mg", apresentacao: "Frasco Ampola", via: "EV (via Exclusiva)", observacao: "Exige justificativa H.D.A." }, //[cite: 2]
    { nome: "Fluconazol 150mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Nistatina 100.000 UI/mL", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Nistatina 25.000UI/g", apresentacao: "Creme", via: "Tópico", observacao: "" }, //[cite: 2]

    // Anti-histamínicos
    { nome: "Dexclorfeniramina 0,4mg/ml", apresentacao: "Solução", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Loratadina 10mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Prometazina 25mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Prometazina 50mg/2mL", apresentacao: "Ampola", via: "IM (via exclusiva)", observacao: "" }, //[cite: 2]

    // Antivirais
    { nome: "Aciclovir 200mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Aciclovir 250mg", apresentacao: "Frasco ampola", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Oseltamivir 30mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Oseltamivir 45mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Oseltamivir 75mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Dolutegravir 50mg", apresentacao: "Comprimido", via: "Oral", observacao: "Profilaxia HIV" }, //[cite: 2]
    { nome: "Tenofovir + Lamivudina 300+300mg", apresentacao: "Comprimido", via: "Oral", observacao: "Profilaxia HIV" }, //[cite: 2]

    // Bloqueadores Musculares, Broncodilatadores, Curativos
    { nome: "Suxametônio 100mg", apresentacao: "Frasco ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Cisatracúrio 10mg/5mL", apresentacao: "Ampola", via: "EV (via exclusiva)", observacao: "Sob refrigeração" }, //[cite: 2]
    { nome: "Salbutamol 100mcg/Jato", apresentacao: "Frasco", via: "Inalatório", observacao: "" }, //[cite: 2]
    { nome: "Ipratrópio 20mcg/Jato", apresentacao: "Frasco", via: "Inalatório", observacao: "" }, //[cite: 2]
    { nome: "Colágenase 1,2 UI", apresentacao: "Pomada", via: "Tópico", observacao: "" }, //[cite: 2]
    { nome: "Óleo de Girassol", apresentacao: "Óleo", via: "Tópico", observacao: "" }, //[cite: 2]

    // Diuréticos e Laxativos
    { nome: "Espironolactona 25mg", apresentacao: "Comprimido", via: "Oral", observacao: "Insuf. Cardíaca" }, //[cite: 2]
    { nome: "Furosemida 20mg/2ml", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Furosemida 40mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Hidroclorotiazida 25mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Manitol 20%", apresentacao: "Bolsa 250mL", via: "EV Via Exclusiva", observacao: "Diurético osmótico" }, //[cite: 2]
    { nome: "Glicerina 12%", apresentacao: "Frasco 500mL", via: "Retal", observacao: "Acompanha sonda" }, //[cite: 2]
    { nome: "Glicerina Infantil", apresentacao: "Supositório", via: "Retal", observacao: "" }, //[cite: 2]
    { nome: "Lactulose 667mg/mL", apresentacao: "Solução", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Óleo Mineral 100%", apresentacao: "Frasco", via: "Oral", observacao: "" }, //[cite: 2]

    // Eletrólitos e Repositores
    { nome: "Bicarbonato de Sódio 8,4%", apresentacao: "Ampola 10mL", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Bicarbonato de Sódio 8,4%", apresentacao: "Bolsa 250mL", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Cloreto de Potássio 10%", apresentacao: "Ampola 10mL", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Cloreto de Sódio 10%", apresentacao: "Ampola 10mL", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Gluconato de Cálcio 10mg/ml", apresentacao: "Ampola 10mL", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Sulfato de Magnésio 50%", apresentacao: "Ampola 10mL", via: "EV (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Sais para reidratação 27,9g", apresentacao: "Sachê", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Água Bidestilada", apresentacao: "Ampola 10ml", via: "EV", observacao: "" }, //[cite: 2]
    { nome: "Água Bidestilada", apresentacao: "Frasco 500mL", via: "EV", observacao: "" }, //[cite: 2]
    { nome: "Cloreto de Sódio 0,9%", apresentacao: "Ampola 10mL", via: "EV", observacao: "" }, //[cite: 2]
    { nome: "Cloreto de Sódio 0,9%", apresentacao: "Frasco 100ml", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Cloreto de Sódio 0,9%", apresentacao: "Frasco 500mL", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Glicose 50%", apresentacao: "Ampola 10ml", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Glicose 5%", apresentacao: "Frasco 500mL", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Ringer com Lactato", apresentacao: "Frasco 500mL", via: "EV (via exclusiva)", observacao: "" }, //[cite: 2]

    // Hipoglicemiantes e Hipolipemiantes
    { nome: "Glibenclamida 5mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Insulina Humana NPH 100 UI/mL", apresentacao: "Frasco ampola", via: "SC (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Insulina Humana Regular 100 UI/mL", apresentacao: "Frasco ampola", via: "SC (via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Metformina 850mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Sinvastatina 20MG", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]

    // Vitaminas
    { nome: "Complexo B", apresentacao: "Ampola 2mL", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Tiamina (Vitamina B1) 100mg/1mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]

    // Psicotrópicos (Prescrição em 2 vias)
    { nome: "Codeína 30mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Codeína + Paracetamol 30+500MG", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Fentanila 78,5mcg/ml", apresentacao: "Ampola 10mL", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Morfina 10mg/1 mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Tramadol 100mg/2mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Ácido Valpróico 50mg/mL", apresentacao: "Solução", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Ácido Valpróico 250mg", apresentacao: "Cápsula", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Fenitoína 100mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Fenitoína 250mg/5mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Fenobarbital 100mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Fenobarbital 40mg/ml", apresentacao: "Gotas", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Fenobarbital 200mg/2mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Amitriptilina 25mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Biperideno 2mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Biperideno 5mg/1mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Clorpromazina 25mg", apresentacao: "Comprimidos", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Clorpromazina 40mg/1 mL (4%)", apresentacao: "Gotas", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Clorpromazina 25mg/5 ml", apresentacao: "Ampola", via: "IM (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Haloperidol 5mg", apresentacao: "Comprimidos", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Haloperidol 2mg/ml", apresentacao: "Gotas", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Haloperidol 5mg/1 ml", apresentacao: "Ampola", via: "IM (Via exclusiva)", observacao: "" }, //[cite: 2]
    { nome: "Risperidona 1 mg/mL", apresentacao: "Suspensão", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Clonazepam 2,5mg/mL", apresentacao: "Gotas", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Diazepam 10mg", apresentacao: "Comprimido", via: "Oral", observacao: "" }, //[cite: 2]
    { nome: "Diazepam 10mg/2mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Midazolam 5mg/5mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Midazolam 15mg/3mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" }, //[cite: 2]
    { nome: "Midazolam 50mg/10mL", apresentacao: "Ampola", via: "IM/EV", observacao: "" } //[cite: 2]
];

const medicamentosBarreiro = [
    // Relação REMUME PBH - Itens liberados para as UPAs (nível de acesso: "Urgência")
    { nome: "Ácido Acetilsalicílico 100 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Adenosina 3 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Água para Injeção", apresentacao: "Ampola 10 ml e Sistema Fechado 500 ml" }, //[cite: 1]
    { nome: "Alteplase 50 mg", apresentacao: "Pó Liofilizado Injetável, FA 50 ml" }, //[cite: 1]
    { nome: "Amiodarona Cloridrato 200 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Amiodarona Cloridrato 50 mg/ml", apresentacao: "Solução Injetável, Ampola 3 ml" }, //[cite: 1]
    { nome: "Amoxicilina 1 g + Ácido Clavulânico 200 mg", apresentacao: "Pó p/ Injetável, FA" }, //[cite: 1]
    { nome: "Amoxicilina 50 mg + Ácido Clavulânico 12,5 mg/ml", apresentacao: "Suspensão Oral" }, //[cite: 1]
    { nome: "Amoxicilina 500 mg + Ácido Clavulânico 125 mg", apresentacao: "Comprimido Revestido" }, //[cite: 1]
    { nome: "Amoxicilina 50 mg/ml", apresentacao: "Pó p/ Suspensão Oral" }, //[cite: 1]
    { nome: "Amoxicilina 500 mg", apresentacao: "Cápsula" }, //[cite: 1]
    { nome: "Ampicilina Sódica 1000 mg", apresentacao: "Pó Liofilizado Injetável, FA" }, //[cite: 1]
    { nome: "Anlodipino Besilato 5 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Atenolol 50 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Atropina Sulfato 0,25 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Azitromicina 40 mg/ml", apresentacao: "Pó p/ Suspensão Oral" }, //[cite: 1]
    { nome: "Azitromicina 500 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Azitromicina 500 mg", apresentacao: "Injetável, FA" }, //[cite: 1]
    { nome: "Benzilpenicilina Benzatina 1.200.000 UI", apresentacao: "Pó Liofilizado Injetável, FA" }, //[cite: 1]
    { nome: "Benzilpenicilina Procaína 300k UI + Potássica 100k UI", apresentacao: "Pó Liofilizado Injetável, FA" }, //[cite: 1]
    { nome: "Bicarbonato de Sódio 8,4%", apresentacao: "Solução Injetável, Ampola 10 ml e Sist. Fechado 250 ml" }, //[cite: 1]
    { nome: "Biperideno Lactato 5 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Captopril 25 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Carbamazepina 200 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Carvão Ativado Pó", apresentacao: "Pacote 50 g" }, //[cite: 1]
    { nome: "Carvedilol 12,5 mg e 3,125 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Cefalexina Monohidratada 50 mg/ml", apresentacao: "Pó p/ Suspensão Oral" }, //[cite: 1]
    { nome: "Cefalexina Monohidratada 500 mg", apresentacao: "Drágea/Comprimido/Cápsula" }, //[cite: 1]
    { nome: "Cefalotina Sódica 1 g", apresentacao: "Pó p/ Solução Injetável, FA" }, //[cite: 1]
    { nome: "Ceftriaxona 1000 mg EV", apresentacao: "Pó Injetável, FA" }, //[cite: 1]
    { nome: "Ceftriaxona 500 mg IM", apresentacao: "Pó Injetável, FA + Diluente" }, //[cite: 1]
    { nome: "Ciprofloxacino 2 mg/ml", apresentacao: "Solução Injetável, Sist. Fechado 100 ml" }, //[cite: 1]
    { nome: "Ciprofloxacino 500 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Clonidina Cloridrato 0,100 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Clopidogrel 75 mg", apresentacao: "Comprimido Revestido" }, //[cite: 1]
    { nome: "Cloreto de Potássio 10%", apresentacao: "Solução Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Cloreto de Sódio 0,9%", apresentacao: "Solução Injetável, Ampola 10 ml e Sist. Fechado (100ml, 250ml, 500ml)" }, //[cite: 1]
    { nome: "Cloreto de Sódio 10%", apresentacao: "Solução Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Deslanosídeo 0,2 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Desloratadina 0,5 mg/ml", apresentacao: "Xarope" }, //[cite: 1]
    { nome: "Dexametasona Fosfato Dissódico 4 mg/ml", apresentacao: "Solução Injetável, Ampola 2,5 ml" }, //[cite: 1]
    { nome: "Dexclorfeniramina Maleato 0,4 mg/ml", apresentacao: "Solução Oral" }, //[cite: 1]
    { nome: "Diazepam 10 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Diazepam 5 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Digoxina 0,25 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Dipirona Sódica 500 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Dipirona Sódica 500 mg/ml", apresentacao: "Solução Oral" }, //[cite: 1]
    { nome: "Dobutamina Cloridrato 12,5 mg/ml", apresentacao: "Solução Injetável, Ampola 20 ml" }, //[cite: 1]
    { nome: "Dolutegravir 50 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Dopamina Cloridrato 5 mg/ml", apresentacao: "Solução Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Doxiciclina 100 mg", apresentacao: "Comprimido Revestido e Comprimido Solúvel" }, //[cite: 1]
    { nome: "Enalapril Maleato 20 mg e 5 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Enoxaparina Sódica 40 mg e 60 mg", apresentacao: "Solução Injetável, Seringa" }, //[cite: 1]
    { nome: "Epinefrina Cloridrato 1 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Escopolamina Butilbrometo 10 mg", apresentacao: "Comprimido Revestido/Drágea" }, //[cite: 1]
    { nome: "Escopolamina Butilbrometo 20 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Escopolamina Butilbrometo 4 mg + Dipirona 500 mg/ml", apresentacao: "Solução Injetável, Ampola 5 ml" }, //[cite: 1]
    { nome: "Espironolactona 100 mg e 25 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Etomidato 2 mg/ml", apresentacao: "Solução Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Fenitoína 100 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Fenitoína 50 mg/ml", apresentacao: "Solução Injetável, Ampola 5 ml" }, //[cite: 1]
    { nome: "Fenobarbital 100 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Fenobarbital Sódico 100 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Fentanila Citrato 78,5 mcg/ml", apresentacao: "Solução Injetável, Ampola 2 ml e FA 10 ml" }, //[cite: 1]
    { nome: "Fitomenadiona (Vitamina K) 10 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Fluconazol 150 mg", apresentacao: "Cápsula" }, //[cite: 1]
    { nome: "Flumazenil 0,1 mg/ml", apresentacao: "Solução Injetável, Ampola 5 ml" }, //[cite: 1]
    { nome: "Furosemida 10 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Furosemida 40 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Gentamicina Sulfato 40 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Glibenclamida 5 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Glicerina 12%", apresentacao: "Solução Frasco/Bolsa 500 ml" }, //[cite: 1]
    { nome: "Gliconato de Cálcio 10%", apresentacao: "Solução Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Glicose 5%", apresentacao: "Solução Injetável, Sist. Fechado 250 ml e 500 ml" }, //[cite: 1]
    { nome: "Glicose 50%", apresentacao: "Solução Injetável, Ampola" }, //[cite: 1]
    { nome: "Haloperidol 5 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Haloperidol 5 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Heparina Sódica 5.000 UI/0,25 ml SC", apresentacao: "Solução Injetável, Ampola" }, //[cite: 1]
    { nome: "Heparina Sódica 5.000 UI/ml EV", apresentacao: "Solução Injetável, FA 5 ml" }, //[cite: 1]
    { nome: "Hidralazina Cloridrato 25 mg", apresentacao: "Drágea" }, //[cite: 1]
    { nome: "Hidroclorotiazida 25 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Hidrocortisona Succinato 100 mg e 500 mg", apresentacao: "Pó p/ Solução Injetável, FA" }, //[cite: 1]
    { nome: "Ibuprofeno 50 mg/ml", apresentacao: "Suspensão Oral Gotas" }, //[cite: 1]
    { nome: "Ibuprofeno 600 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Insulina Humana NPH 100 UI/ml", apresentacao: "Suspensão Injetável, Frasco 10 ml" }, //[cite: 1]
    { nome: "Insulina Humana Regular 100 UI/ml", apresentacao: "Injetável, FA 10 ml" }, //[cite: 1]
    { nome: "Ipratrópio Brometo 0,25 mg/ml", apresentacao: "Solução p/ Inalação" }, //[cite: 1]
    { nome: "Isossorbida Dinitrato 5 mg", apresentacao: "Comprimido Sublingual" }, //[cite: 1]
    { nome: "Isossorbida Mononitrato 40 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Ivermectina 6 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Lactulose 667 mg/ml", apresentacao: "Xarope" }, //[cite: 1]
    { nome: "Lidocaína 10 mg/ml sem vasoconstritor", apresentacao: "Solução Injetável, FA 20 ml" }, //[cite: 1]
    { nome: "Lidocaína 10 mg/ml + Epinefrina", apresentacao: "Solução Injetável, FA 20 ml" }, //[cite: 1]
    { nome: "Lidocaína 20 mg/g", apresentacao: "Gel, Bisnaga 30 g" }, //[cite: 1]
    { nome: "Lidocaína 20 mg/ml sem vasoconstritor", apresentacao: "Solução Injetável, Ampola 5 ml e FA 20 ml" }, //[cite: 1]
    { nome: "Loratadina 1 mg/ml", apresentacao: "Xarope" }, //[cite: 1]
    { nome: "Loratadina 10 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Losartana Potássica 50 mg", apresentacao: "Comprimido Revestido" }, //[cite: 1]
    { nome: "Manitol 20%", apresentacao: "Solução Injetável, Sist. Fechado 250 ml" }, //[cite: 1]
    { nome: "Meglumina Antimoniato 1,5g", apresentacao: "Injetável, Ampola 5 ml" }, //[cite: 1]
    { nome: "Metformina Cloridrato 850 mg", apresentacao: "Comprimido Revestido" }, //[cite: 1]
    { nome: "Metildopa 250 mg", apresentacao: "Comprimido Revestido" }, //[cite: 1]
    { nome: "Metoclopramida Cloridrato 10 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Metoclopramida Cloridrato 5 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Metoprolol Tartarato 1 mg/ml", apresentacao: "Solução Injetável, Ampola 5 ml" }, //[cite: 1]
    { nome: "Metronidazol 250 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Metronidazol 500 mg", apresentacao: "Injetável, Sist. Fechado 100 ml" }, //[cite: 1]
    { nome: "Midazolam 5 mg/ml", apresentacao: "Solução Injetável, Ampola 3 ml e 10 ml" }, //[cite: 1]
    { nome: "Morfina Sulfato 10 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Morfina Sulfato 30 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Naloxona Cloridrato 0,4 mg/ml", apresentacao: "Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Nitroglicerina 5 mg/ml", apresentacao: "Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Norepinefrina Hemitartarato 2 mg/ml", apresentacao: "Injetável, Ampola 4 ml" }, //[cite: 1]
    { nome: "Norfloxacino 400 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Octreotida Acetato 0,05 mg/ml e 0,1 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Óleo Mineral Puro", apresentacao: "Frasco 100 ml" }, //[cite: 1]
    { nome: "Omeprazol 20 mg", apresentacao: "Cápsula" }, //[cite: 1]
    { nome: "Omeprazol Sódico 40 mg", apresentacao: "Pó p/ Solução Injetável, FA" }, //[cite: 1]
    { nome: "Ondansetrona 2 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Ondansetrona Cloridrato 4 mg", apresentacao: "Comprimido Dispersível" }, //[cite: 1]
    { nome: "Oseltamivir Fosfato 30, 45, 75 mg", apresentacao: "Cápsula" }, //[cite: 1]
    { nome: "Oxacilina 500 mg", apresentacao: "Pó p/ Solução Injetável, FA" }, //[cite: 1]
    { nome: "Paracetamol 200 mg/ml", apresentacao: "Solução Oral" }, //[cite: 1]
    { nome: "Prednisona 20 mg e 5 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Prometazina Cloridrato 25 mg/ml", apresentacao: "Solução Injetável, Ampola 2 ml" }, //[cite: 1]
    { nome: "Propranolol Cloridrato 40 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Rifampicina + Isoniazida + Pirazinamida + Etambutol", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Rifampicina 20 mg/ml", apresentacao: "Suspensão Oral" }, //[cite: 1]
    { nome: "Rifampicina 300 mg", apresentacao: "Cápsula" }, //[cite: 1]
    { nome: "Ringer com Lactato", apresentacao: "Injetável, Sist. Fechado 500 ml" }, //[cite: 1]
    { nome: "Ritonavir 100 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Rocurônio Brometo 10 mg/ml", apresentacao: "Solução Injetável, FA 5 ml" }, //[cite: 1]
    { nome: "Sais para Reidratação Oral", apresentacao: "Pó, Envelope 27,9 g" }, //[cite: 1]
    { nome: "Salbutamol Sulfato 100 mcg/jato", apresentacao: "Aerossol" }, //[cite: 1]
    { nome: "Salbutamol Sulfato 5 mg/ml", apresentacao: "Solução p/ Nebulização" }, //[cite: 1]
    { nome: "Simeticona 75 mg/ml", apresentacao: "Emulsão Oral" }, //[cite: 1]
    { nome: "Sinvastatina 40 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Sorbitol 714 mg + Laurilsulfato", apresentacao: "Solução Retal" }, //[cite: 1]
    { nome: "Sulfadiazina de Prata Micronizada 1%", apresentacao: "Creme" }, //[cite: 1]
    { nome: "Sulfametoxazol 40 mg + Trimetoprima 8 mg/ml", apresentacao: "Suspensão Oral" }, //[cite: 1]
    { nome: "Sulfametoxazol 400 mg + Trimetoprima 80 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Sulfametoxazol 80 mg + Trimetoprima 16 mg/ml", apresentacao: "Solução Injetável, Ampola 5 ml" }, //[cite: 1]
    { nome: "Sulfato de Magnésio 50%", apresentacao: "Solução Injetável, Ampola 10 ml" }, //[cite: 1]
    { nome: "Suxametônio Cloreto 100 mg", apresentacao: "Pó Liofilizado Injetável, FA" }, //[cite: 1]
    { nome: "Tenofovir 300 mg + Lamivudina 300 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Tenoxicam 20 mg", apresentacao: "Pó Liofilizado p/ Solução Injetável, FA" }, //[cite: 1]
    { nome: "Tiamina Cloridrato 100 mg/ml", apresentacao: "Solução Injetável, Ampola 1 ml" }, //[cite: 1]
    { nome: "Tramadol 50 mg/ml", apresentacao: "Solução Injetável, Ampola" }, //[cite: 1]
    { nome: "Varfarina Sódica 5 mg", apresentacao: "Comprimido" }, //[cite: 1]
    { nome: "Verapamil Cloridrato 80 mg", apresentacao: "Comprimido Revestido" }, //[cite: 1]
    { nome: "Vitaminas do Complexo B", apresentacao: "Solução Injetável, Ampola 2 ml" } //[cite: 1]
];

module.exports = {
    medicamentosAcrizioMenezes,
    medicamentosBarreiro
};
